apiVersion: v1
kind: Secret
metadata:
    name: cluster-secrets
    namespace: flux-system
stringData:
    SECRET_DOMAIN: ENC[AES256_GCM,data:hM3QpjJzmMCVKgrSZObQkcvAZ8j+854=,iv:YJ+lYpJTsSOqZXy/TSlAdFsyC2Az52KlM68Fbuf3ceM=,tag:kYsnFnq0BTwCjnfY5bfruA==,type:str]
    SECRET_CLOUDFLARE_EMAIL: ENC[AES256_GCM,data:K95ABQYwaY+wT2rrS3HZC4LRY+A4tg==,iv:80gS+k+CNHa7GRKdJ5vbLz61je4Q/oz+VrKnqvymHNw=,tag:3nf/9TalSfaOqO9kVVcDqA==,type:str]
    SECRET_CLOUDFLARE_TUNNEL_ID: ENC[AES256_GCM,data:CdYYOC9FNze2rQDBKwQvAmP9Os/QeuNrQn3HPYhxT7xiSobl,iv:IGHkduWUJ7DjIn6Iw9zbFuL+zG9MGFDkB0/4hakBpS0=,tag:Y+ir3hDRa80rjsXXzKpXgw==,type:str]
    SECRET_CLOUDFLARE_TOKEN: ENC[AES256_GCM,data:5Ku/kTja4YqfAgtXLGninQDZhl12LOg6mN9sCYdaLTQxtuSAtL+otzTnqyo=,iv:RzEGhfeZaxoF9R6Ixf6MCvPdKNTfyhXG2epIrYa70oc=,tag:NbWOuVfbKj/YYQbCrnZfbA==,type:str]
    SECRET_CLOUDFLARE_KEY: ENC[AES256_GCM,data:US0j2FyH2k1xnWEMoyNifPAcueLXTk4DpWPRUqH1UEryj5njyQ==,iv:BPGvDKGJo43eHbIFsS58Ch9dF0IYs9LkTRp2BQQTSuA=,tag:CvIuxu4HnOMsPUNS8zKbxA==,type:str]
    TIMEZONE: ENC[AES256_GCM,data:1If4SxRcDk8sFAhnofqG,iv:lvnc95PWuzpH1TiNAHdU0cI4VoQdVHHRpTCRwgM1XBA=,tag:fPerr71gA2TcwRtEcmEYaA==,type:str]
    WEAVE_DASHBOARD_PASSWORD: ENC[AES256_GCM,data:UslgkHHGyd9LF8EW4vmij5wAyBFmDrgxGVjVmx6Icm4LtM4qJU6P1fZnqmaztx4G7HrHqZATMwWflzm/ZlqT4A==,iv:XM1IuE3YXwkM5GkxKyJKEN9vCd+Nti9sI5GEuyzJFaU=,tag:xuIMZ0ZQIxmCHVlFPA6bcw==,type:str]
    SECRET_ALERTMANAGER_UPTIMEROBOT_HEARTBEAT_TOKEN: ENC[AES256_GCM,data:E5GA4wp4xZ614FpKDp3qlYRuEySryPF+nQJgmLYZkTk9Q0TEoRe23cegTW3UXyKMqGjU,iv:hMvKP5BMiaoyC0UzMPGsl7UJjoOrOXxB67RGMe6a8cM=,tag:NwpNjrNeCnze+UXgRzk3zg==,type:str]
    SECRET_ALERTMANAGER_PUSHOVER_TOKEN: ENC[AES256_GCM,data:BaJUAPCVzsfGfXn+SfWoeUAQI/V2A9QBAErx4+TR,iv:fsfnlu0ct+sEvwIkw6q8SSB5u7qyFEck2L0QZ2uk340=,tag:Cs0efJTGGqce5Q/4WiEOOw==,type:str]
    SECRET_ALERTMANAGER_PUSHOVER_USER_KEY: ENC[AES256_GCM,data:pVsa2EZ8EVVtBo1fVF30mant2LqQcsMS7GuG44Hfzg==,iv:PotKCSxcDZCxELNsvpoNh3Ui5d+I6gJ+gNd4MXvA3Rw=,tag:dS2YxSZXcx0h8WsfzT65WQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1472mvfqk0pryyv9w7q0qyv83twgtptu5tnhca9u0w9fqkvte4c9sktl244
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAxOWdwSzMzVUsvdGNUV2g0
            c2hSOGxYUnQ0V3FlV3c2dnJ2clFBaVNybW1BCnhaNEJiYmh5R05nbnk0ZUhyRnRS
            OEtkQWVxUVpnQmtHUVh5YWR2UlEzczgKLS0tIHhwazhwTW9JTFZOQkZIRnZvOStx
            SmhBbjZqS09JcStXaUYxNWpaQlloZFkKfVYJCACFxhRyU7g2TFczxONrszcd0v4U
            EVzZU9JuG1lYofY5TgRVrieVLNrhkiYb5ixNb/Ti+hYSAP5s0L/mwA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-05-13T23:50:21Z"
    mac: ENC[AES256_GCM,data:+JQZeVo90LEdUQo4LGwE5FzLXN09ch0yURFvuTKwiEFTJvTHf7MnjmyWqVuzZ09khu5moLzxGvpexcjjPfgvtyUHfsWpsF1Sa8MknJhBHDhtoe18xevAOhMOtewLpGTdCi7A6KGpVT5svM/5uQePC9xsu+McJLJfXftrXAqjKxs=,iv:qcLjgFxRHV2UzOy4akkWKR3GFfHQVbktsL+CuzKZaBI=,tag:z5Ze86ICTFjNT6iEtriVVg==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
