apiVersion: v1
kind: Secret
metadata:
    name: doppler-secret
    namespace: kube-system
type: Opaque
stringData:
    dopplerToken: ENC[AES256_GCM,data:lTOAzzuT7xIxSRbJ4GRf0/5tg75ALB79kQRA4uwWnhaFkT5prPcJTfSJbsjv0XMaOSaHxo0=,iv:WVI3h2Eo52TiHeaNDUkEvGWoRmfvEzygY6LNz8DBW+k=,tag:P6JYS4ZiUh5GC2Rt+HQ2dQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1472mvfqk0pryyv9w7q0qyv83twgtptu5tnhca9u0w9fqkvte4c9sktl244
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA5dDRqdmsycGovdXM5TTZn
            YmJmN05naEdQNkttWStaSlNjUGZWWlkvakRRCmpmRlg0RFM4UUR0bzVsYkRFRkNE
            R2MzRjJWZUNuY0xUUjVSVnRGRThrWW8KLS0tIGFMRnhkK05zbEtlYTJmTmxxN1Bw
            Y0pFc2piZGZPWEVIby9CWXlqV0xmczQKynKW3BlRq2MTy+GCosQk86vpuUKB8Ce4
            Lbhi/QQBk8Hed8IN8BedcVFfQlQseBaX41XiBBSTivT7s27S66OiRw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-05-13T23:12:38Z"
    mac: ENC[AES256_GCM,data:Eqp7V9O2WSf7fvD2yi0HTlqvYTYfuXOj9tlZJ3RNfXunzqxgCh4n5AIhPsZmVeDQGA0Ptoth4ng/FrmwiEsopPtttVspMKyigfy7ej07PL/YYJa/R30sh6ZkkNBpnnNwi0I33aS9v3EzrcxjqLUGE/nBAkjDvjXZLOn7nrd2tc0=,iv:xlW4BbvOSwMt1vP06BFkyXVkBXSKVxpYW1BN1PN3n78=,tag:3TxDApBDnE07XX7AXh1EnQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
