---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
metadata:
  name: infra-controllers
resources:
  - cert-manager.yaml
  - external-dns.yaml
  - external-secrets.yaml
  - k8s-gateway.yaml
  - metallb.yaml
  - namespaces.yaml
  - nginx-ingress.yaml
  - rook-ceph.yaml
