---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - cluster-issuers.yaml
  - cluster-secret-store.yaml
  - metallb.yaml
  - nginx-certificates.yaml
  - rook-ceph-cluster.yaml
